### ISSUE TITLE
fix(streaming): implement checkpoint store state value equality

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#11222]
## Problem

A normal Release build on main `bfef5e641629db33dcad34f3190ce87010359cb6` fails with CA1815 for the new public readonly `StreamCheckpointStoreState` struct introduced by #11154. CA1815 was enabled for Orleans.Streaming by the earlier merged #11166, which predates this type.

## Reproduction

Windows, .NET SDK 10.0.401 (repository global.json 10.0.400, roll-forward major):

```powershell
dotnet test --project test\Orleans.Runtime.Internal.Tests\Orleans.Runtime.Internal.Tests.csproj --framework net10.0 --configuration Release --no-restore --filter-class "UnitTests.ClusterServices.*" --filter-trait "Provider=None" --minimum-expected-tests 1 --timeout 3m --report-trx
```

The build fails before test execution:

```text
src\Orleans.Streaming\Checkpointers\StreamCheckpointStoreState.cs(8,24): error CA1815: StreamCheckpointStoreState should override Equals
src\Orleans.Streaming\Checkpointers\StreamCheckpointStoreState.cs(8,24): error CA1815: StreamCheckpointStoreState should override the equality (==) and inequality (!=) operators
```

This was observed while validating an isolated coordination branch rebased on the main commit above. The affected type is unchanged from main and is unrelated to that branch's coordination implementation.

## Expected outcome

`StreamCheckpointStoreState` defines consistent value equality and hashing for its checkpoint and backend-version fields, with corresponding operators, focused equality tests, and regenerated public API output. A normal Release build passes with the existing analyzer policy.

## Related work

- #11154 introduced the checkpoint state type.
- #11166 enabled and addressed CA1815 for earlier value types, but does not cover this later addition.

Searches for `StreamCheckpointStoreState`, `CA1815`, and checkpoint equality found no existing issue or corrective PR for this new failure.
