### PR TITLE
test(codegen): pass cancellation token to diagnostics

### LINKED ISSUE #10856: CI failure: xUnit1051 blocks all test jobs after #10845
Current `main` fails before tests execute after #10845 removed the repository-wide xUnit1051 suppression.

The compiler reports:

```
test/Orleans.CodeGenerator.Tests/GeneratedWarningSuppressionTests.cs(117,30): error xUnit1051: Calls to methods which accept CancellationToken should use TestContext.Current.CancellationToken
```

Affected `main` runs:

- #10845 merge commit `aa72a8691d1ac71775c0ffa041fc89943837f2e9`: https://github.com/dotnet/orleans/actions/runs/33118034320
- Subsequent `main` commit `00d1a220a3e810b6d7f18216662dbba32d53d57e`: https://github.com/dotnet/orleans/actions/runs/33119590251

The same build failure blocks every provider job on PR #10855 before the reminder tests can run, including Azure Storage, SQL Server, and Cosmos DB: https://github.com/dotnet/orleans/actions/runs/33119980884

The invocation at line 117 is part of a generated-warning suppression test and needs cancellation propagation or a targeted analyzer exemption consistent with the test's intent.

### PR DESCRIPTION
**Pull request by ReubenBond**
Fixes #10856.

Passes `TestContext.Current.CancellationToken` to Roslyn diagnostic collection in `GeneratedWarningSuppressionTests`, satisfying xUnit1051 and restoring warning-as-error builds for the test project.

This keeps cancellation flowing through the potentially long-running diagnostic operation without changing the test's assertions or generated-code behavior.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/orleans/pull/10878)

### CODE REVIEW

**Comment by ReubenBond** [comment]
CI restore failures in this run are unrelated to this change: Azure DevOps NuGet feeds are returning HTTP 500 / `Maximum waiter thread limit 500 is reached` across 21+ matrix jobs. Local `dotnet build Orleans.slnx -bl` succeeds at `7057ea85e1`, and the focused tests pass. Tracked in #10881; failed jobs should be rerun after feed recovery.

**Comment by ReubenBond** [comment]
The Azure DevOps NuGet feed recovered. Failed-job rerun attempt 2 completed successfully: all 75 PR checks now pass.
