### ISSUE TITLE
CI failure: xUnit1051 blocks all test jobs after #10845

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#10856]
Current `main` fails before tests execute after #10845 removed the repository-wide xUnit1051 suppression.

The compiler reports:

```
test/Orleans.CodeGenerator.Tests/GeneratedWarningSuppressionTests.cs(117,30): error xUnit1051: Calls to methods which accept CancellationToken should use TestContext.Current.CancellationToken
```

Affected `main` runs:

- #10845 merge commit `aa72a8691d1ac71775c0ffa041fc89943837f2e9`: https://github.com/dotnet/orleans/actions/runs/33118034320
- Subsequent `main` commit `00d1a220a3e810b6d7f18216662dbba32d53d57e`: https://github.com/dotnet/orleans/actions/runs/33119590251

The same build failure blocks every provider job on PR #10855 before the reminder tests can run, including Azure Storage, SQL Server, and Cosmos DB: https://github.com/dotnet/orleans/actions/runs/33119980884

The invocation at line 117 is part of a generated-warning suppression test and needs cancellation propagation or a targeted analyzer exemption consistent with the test's intent.
